### ISSUE TITLE
How is a failed host identified in the SNMP trap?

### ISSUE THREAD

**Issue by rendhalver** [jamtur01/puppet-snmp#4]
I am in the process of testing this to see if it will do what we need in our environment.
I am unsure what information will be sent to the SNMP trap.

Can you please clarify?

**Comment by jamtur01** [comment]
@rendhalver Honestly it's been 5 years since I wrote this and I am not sure what it sends. Test it and try I guess? Cheers.

**Comment by rendhalver** [comment]
I am testing this on a recent PE master (v2015.3.2) and I believe I have set it up correctly.
I see nothing in the log files that resembles the error messages it generates and I also see nothing attempting to send anything to the snmp server.

**Comment by jamtur01** [comment]
I am afraid I am not sure how report processors work on PE. It's been several years since I used PE. The only thing I can suggest is to turn on verbose and debug options?
